[workspace]
members = ["valera", "valera-*", "tests", "examples/*"]
default-members = ["valera", "valera-*"]
# exclude = [] // could be used in case one of the above is empty (most often that will be an example. With this could create crates for them preventively
resolver = "2"